### ISSUE TITLE
backend CLI option ignored if passed in different order

### ISSUE THREAD

**Issue by mratsim** [diku-dk/futhark-benchmarks#10]
I tried running benchmarks with the following command:

```
futhark bench * --json --backend=opencl --ignore-files /lib/
```

but the benchmarked used CPU.

In this order however, benchmarks are correctly built for OpenCL.

```
futhark bench * --backend=opencl --json --ignore-files /lib/
```

**Comment by athas** [comment]
I think that is because the former is interpreted as

```
futhark bench * --json=--backend=opencl --ignore-files /lib/
```

while the latter is interpreted as

```
futhark bench * --backend=opencl --json=--ignore-files /lib/
```

I.e. the source of the problem is that `--json` requires an argument (a filename for the JSON), and unfortunately it does not seem to insist on an `=`, but will just gobble up the next option.  I *think* this is expected `getopt_long()` behaviour, but I can't say I like it.

**Comment by mratsim** [comment]
Ah I see, I thought from the README that `--json` had a default filename output.
> If you wish to analyse the performance results with a program, the --json option to futhark bench may be useful.

**Comment by athas** [comment]
Good point. I will clarify in the README.
